### ISSUE TITLE
Server hangs on map screen

### ISSUE THREAD

**Issue by Tinter** [Tinter/Tinter-Furniture#20]
Server will be stuck on the loading screen when using the script.
Only if there is an admin logged in, if there is no admin logged in it will let players through.
Seems like a issue on the server.

**Comment by Tinter** [comment]
Seemingly not caused by any of the actual code.
Tested with a waitUntil in the init by garrus.

**Comment by Tinter** [comment]
Happens with one player on a dedicated server when voted as admin.
Not in singleplayer with briefing, nor on a listen server.

**Comment by Tinter** [comment]
Hangs on dedicated server, one player, not voted as admin.

**Comment by Tinter** [comment]
Note: Tested servers have headless client connected, but not slotted.

**Comment by G3rrus** [comment]
https://github.com/Tinter/Tinter-Furniture/blob/cb4b0b7b8f604c520b03fa84a0c5a1a61f85ad43/furniture/functions/fn_init.sqf#L39

This makes it hang. Not sure why though.

**Comment by Tinter** [comment]
Fixed with commit 57e2023.
Now it only sleeps in singleplayer.
